# Generated by Django 4.2.5 on 2023-09-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_expect',
            field=models.TextField(null=True),
        ),
    ]
