# Generated by Django 4.2.5 on 2023-09-24 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_question_responses_via_email_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
