# Generated by Django 4.2.5 on 2023-09-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='responses_via_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
