# Generated by Django 4.2.5 on 2023-10-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='branch_images/'),
        ),
    ]
